### ISSUE TITLE
ModuleNotFoundError: No module named 'ocr'

### ISSUE THREAD

**Issue by Hiwen** [wuditken/MillionHeroes#24]
请问有朋友遇到下面这个问题吗？
我用的PyCharm运行的，可能和PyCharm项目的 Virtualenv 有关，但是我没搞明白！
希望大神指点一下，谢谢

E:\Dev\MyMH\venv\Scripts\python.exe E:/Dev/MyMH/hero.py
Traceback (most recent call last):
  File "E:/Dev/MyMH/hero.py", line 3, in <module>
    from aip import AipOcr
  File "E:\Dev\Python\venv\Lib\site-packages\aip\__init__.py", line 6, in <module>
    from ocr import AipOcr
ModuleNotFoundError: No module named 'ocr'

**Comment by wuditken** [comment]
少模块 发自网易邮箱大师 在2018年01月13日 18:56，Hiwen 写道： 请问有朋友遇到下面这个问题吗？ 我用的PyCharm运行的，可能和PyCharm项目的 Virtualenv 有关，但是我没搞明白！ 希望大神指点一下，谢谢 E:\Dev\MyMH\venv\Scripts\python.exe E:/Dev/MyMH/hero.py Traceback (most recent call last): File "E:/Dev/MyMH/hero.py", line 3, in from aip import AipOcr File "E:\Dev\Python\venv\Lib\site-packages\aip_init_.py", line 6, in from ocr import AipOcr ModuleNotFoundError: No module named 'ocr' — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wuditken** [comment]
要安装百度的api，看主页的使用教程。把模块都安装了 发自网易邮箱大师 在2018年01月13日 19:08，18744763485@139.com 写道： 少模块 发自网易邮箱大师 在2018年01月13日 18:56，Hiwen 写道： 请问有朋友遇到下面这个问题吗？ 我用的PyCharm运行的，可能和PyCharm项目的 Virtualenv 有关，但是我没搞明白！ 希望大神指点一下，谢谢 E:\Dev\MyMH\venv\Scripts\python.exe E:/Dev/MyMH/hero.py Traceback (most recent call last): File "E:/Dev/MyMH/hero.py", line 3, in from aip import AipOcr File "E:\Dev\Python\venv\Lib\site-packages\aip_init_.py", line 6, in from ocr import AipOcr ModuleNotFoundError: No module named 'ocr' — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lllmmmfff** [comment]
C:\Users\gzlia>pip install baidu-aip
Requirement already satisfied: baidu-aip in c:\python35\lib\site-packages

貌似装过了，但是
Traceback (most recent call last):
  File "C:\Users\gzlia\Desktop\MillionHeroes-master\hero.py", line 3, in <module>
    from aip import AipOcr
ModuleNotFoundError: No module named 'aip'

**Comment by Hiwen** [comment]
我后来在 PyCharm的Terminal里面，把pip install ... 再执行了一下，再在Terminal里面执行了一下 python hero.py  然后就好了！  谢谢啦
